server:
  port:
    ${SERVER_PORT:8081}
  servlet:
    session:
      timeout: 15m # 15 minutes, remove this line if you want the default session timeout [sessionManagement in security config]
#      cookie:
#        name: AUTH_SERVER_SESSION_ID

spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/core_db
    username: postgres
    password: Bi$mill4h
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false     # enable this to show the generated SQL in the console
    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  security:
    oauth2:
      resourceserver:
        jwt:
          enabled: false  # We're using opaque tokens
      authorizationserver:
        issuer-uri: http://localhost:${server.port}
        token:
          access-token-format: opaque

#springdoc:
#  api-docs:
#    path: /auth-api-docs
#  packages-to-scan: com.project.auth.controller
#  swagger-ui:
#    filter: true
#    operationsSorter: method
#    path: /quartz-documentation
#    tagsSorter: alpha
#    tryItOutEnabled: true
#openapi:
#  dev-url: http://localhost:${server.port}
#  prod-url: https://prod-api.com

logging:
  level:
    org:
      springframework:
        security: DEBUG # This sets DEBUG for all of org.springframework.security.*
        oauth2: # This covers org.springframework.security.oauth2.*
          server:
            authorization: DEBUG # This is specific for org.springframework.security.oauth2.server.authorization.*
        web: # This 'web' is a sibling of 'security' under 'springframework'
          filter:
            OncePerRequestFilter: DEBUG
          client: # This corresponds to 'org.springframework.web.client'
            RestTemplate: DEBUG

    com:
      zaxxer:
        hikari: DEBUG